[PHP]
post_max_size = 100M
upload_max_filesize = 100M
variables_order = EGPCS
pcov.directory = .

[opcache]
opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
; Не проверять изменения файлов каждый запрос (проверять раз в 60 сек)
opcache.revalidate_freq = 60
opcache.validate_timestamps = 1
; Preload — кэшировать файлы в память
opcache.preload_user = www-data
opcache.jit_buffer_size = 64M
opcache.jit = tracing
